server:
  port: 7070
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abel74176537/DAD-2025-2-main.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: root
      password: 123456